use_frameworks!

target 'Demo' do
  # Uncomment the line below for CocoaPods <= 1.8
  #source 'https://github.com/CocoaPods/Specs.git'
  source 'https://cdn.cocoapods.org/'
  source 'git@github.com:berbix/berbix-ios-spec.git'

  pod 'Berbix', '3.0.1'
end
